# Generated by Django 3.1.13 on 2021-09-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20210901_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='en_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='имя на английском'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='jp_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='имя на японском'),
        ),
    ]
